### ISSUE TITLE
Fatal error: Uncaught Error: Class "WebblerTabs" & "WebblerListing" not found

### ISSUE THREAD

**Issue by arbialexandri** [bramley/phplist-plugin-common#22]
Upon upgrading the plugin to the most recent version, 3.32.0+20231221, PHPList goes blank! After enabling the error reporting, as described here https://www.phplist.org/manual/books/phplist-manual/page/troubleshooting-techniques, the following errors can be captured:

```
Fatal error: Uncaught Error: Class "WebblerTabs" not found in /www/phpList/3.6.14/lists/admin/plugins/Common/Tabs.php:22 Stack trace: #0 /www/phpList/3.6.14/lists/admin/plugins/CommonPlugin/vendor/composer/ClassLoader.php(578): include() #1 /www/phpList/3.6.14/lists/admin/plugins/CommonPlugin/vendor/composer/ClassLoader.php(432): Composer/Autoload/ClassLoader::Composer/Autoload/{closure}('/www/php...') #2 /www/phpList/3.6.14/lists/admin/plugins/CommonPlugin/CommonPlugin_XXX.php(94): Composer/Autoload/ClassLoader->loadClass('phpList/plugin/...') #3 /www/phpList/3.6.14/lists/admin/plugins/CommonPlugin/vendor/composer/ClassLoader.php(578): include('/www/php...') #4 /www/phpList/3.6.14/lists/admin/plugins/CommonPlugin/vendor/composer/ClassLoader.php(432): Composer/Autoload/ClassLoader::Composer/Autoload/{closure}('/www/php...') #5 /www/phpList/3.6.14/lists/admin/plugins/BounceStatisticsPlugin.php(70): Composer/Autoload/ClassLoader->loadClass('CommonPlugin_I1...') #6 /www/phpList/3.6.14/lists/admin/pluginlib.php(163): BounceStatisticsPlugin->activate() #7 /www/phpList/3.6.14/lists/admin/connect.php(81): include_once('/www/php...') #8 /www/phpList/3.6.14/lists/admin/index.php(106): require_once('/www/php...') #9 {main} thrown in /www/phpList/3.6.14/lists/admin/plugins/Common/Tabs.php on line 22
```

```
Fatal error: Uncaught Error: Class "WebblerListing" not found in /www/phpList/3.6.14/lists/admin/plugins/Common/WebblerListing.php:20 Stack trace: #0 /www/phpList/3.6.14/lists/admin/plugins/CommonPlugin/vendor/composer/ClassLoader.php(578): include() #1 /www/phpList/3.6.14/lists/admin/plugins/CommonPlugin/vendor/composer/ClassLoader.php(432): Composer/Autoload/ClassLoader::Composer/Autoload/{closure}('/www/php...') #2 /www/phpList/3.6.14/lists/admin/plugins/CommonPlugin/CommonPlugin_XXX.php(97): Composer/Autoload/ClassLoader->loadClass('phpList/plugin/...') #3 /www/phpList/3.6.14/lists/admin/plugins/CommonPlugin/vendor/composer/ClassLoader.php(578): include('/www/php...') #4 /www/phpList/3.6.14/lists/admin/plugins/CommonPlugin/vendor/composer/ClassLoader.php(432): Composer/Autoload/ClassLoader::Composer/Autoload/{closure}('/www/php...') #5 /www/phpList/3.6.14/lists/admin/plugins/BounceStatisticsPlugin.php(70): Composer/Autoload/ClassLoader->loadClass('CommonPlugin_I1...') #6 /www/phpList/3.6.14/lists/admin/pluginlib.php(163): BounceStatisticsPlugin->activate() #7 /www/phpList/3.6.14/lists/admin/connect.php(81): include_once('/www/php...') #8 /www/phpList/3.6.14/lists/admin/index.php(106): require_once('/www/php...') #9 {main} thrown in /www/phpList/3.6.14/lists/admin/plugins/Common/WebblerListing.php on line 20
```

Removing the following lines/blocks from /CommonPlugin_XXX.php file, allows PHPList to load again, but I am not sure if it will be fully functional as intended.

lines 94 to 96
```
class CommonPlugin_Tabs extends phpList\plugin\Common\Tabs
{
}
```

lines 100 to 102
```
class CommonPlugin_WebblerListing extends phpList\plugin\Common\WebblerListing
{
}
```

**Comment by bramley** [comment]
Thanks, it has been fixed now. See https://discuss.phplist.org/t/500-error-after-updating-the-commonplugin/9296/2

**Comment by arbialexandri** [comment]
After the new changes/release, the plugin can be updated/installed without an issue. Thank you.
